server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hire_car?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  servlet:
    multipart:
        # 上传一个文件最大值,默认1Mb
      max-file-size: 100MB
        # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true


#servlet:
#  multipart:
#    enabled: true
#    max-file-size: 20MB
#    max-request-size: 200MB


